### ISSUE TITLE
Self-directed edges for nodes in habitat

### ISSUE THREAD

**Issue by rdnfn** [ai4er-cdt/gtc-biodiversity#34]
**Description:** it appears that the `GeoGraph.add_habitat()` method adds edges between nodes and themselves, but we probably don't want this as these edges don't have any meaning.

**Example:**
In the example here we have 2 nodes and 3 edges:

![Screenshot 2021-03-01 at 19 16 12](https://user-images.githubusercontent.com/75615911/109547203-04a3ff00-7ac3-11eb-9034-88672cbaaa8f.png)

**Comment by herbiebradley** [comment]
Ah my bad, I think I prevented this in one version of the function but then it got removed somewhere along the way.

Since the fix is just to change `if nbr in invalid_idx:` to `if nbr != node or nbr in invalid_idx:` in the add edges loop, should I bother with a PR for this or just add a quick commit to the graph-analysis branch?

**Comment by rdnfn** [comment]
Ah right, thanks for getting back so quickly! There is no rush on my side, since it doesn't break any of my functions (they just draw zero length edges). So I am happy either way, quick commit or within the bigger PR.

**Comment by Croydon-Brixton** [comment]
> if nbr != node or nbr in invalid_idx:

@herbiebradley @rdnfn 
Added the fix in [acc7874](https://github.com/ai4er-cdt/gtc-biodiversity/pull/28/commits/acc78748d798b72574c9e6eccd2123bf1a069a6a)
